# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'atividades',
                'verbose_name_plural': 'atividades',
                'verbose_name': 'atividade',
            },
        ),
        migrations.CreateModel(
            name='Encontro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_realizao', models.DateField()),
            ],
            options={
                'db_table': 'encontros',
                'verbose_name_plural': 'encontros',
                'verbose_name': 'encontro',
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'equipes',
                'verbose_name_plural': 'equipes',
                'verbose_name': 'equipe',
            },
        ),
        migrations.CreateModel(
            name='EquipeTutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_service.Equipe')),
            ],
            options={
                'db_table': 'equipe_tutor',
                'verbose_name_plural': 'equipe_tutor',
                'verbose_name': 'equipe_tutor',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'eventos',
                'verbose_name_plural': 'eventos',
                'verbose_name': 'evento',
            },
        ),
        migrations.CreateModel(
            name='EventoEquipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_service.Equipe')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_service.Evento')),
            ],
            options={
                'db_table': 'evento_equipe',
                'verbose_name_plural': 'evento_equipe',
                'verbose_name': 'evento_equipe',
            },
        ),
        migrations.CreateModel(
            name='EventoInscrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_service.Evento')),
            ],
            options={
                'db_table': 'evento_inscrito',
                'verbose_name_plural': 'evento_inscrito',
                'verbose_name': 'evento_inscrito',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('dir_audio', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web_service.Atividade')),
            ],
            options={
                'db_table': 'feedback',
                'verbose_name_plural': 'feedbacks',
                'verbose_name': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nasc', models.DateField()),
                ('escola', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'inscritos',
                'verbose_name_plural': 'inscritos',
                'verbose_name': 'inscrito',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tutores',
                'verbose_name_plural': 'tutores',
                'verbose_name': 'tutor',
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='inscrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web_service.Inscrito'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web_service.Tutor'),
        ),
        migrations.AddField(
            model_name='eventoinscrito',
            name='inscrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_service.Inscrito'),
        ),
        migrations.AddField(
            model_name='evento',
            name='equipes',
            field=models.ManyToManyField(through='web_service.EventoEquipe', to='web_service.Equipe'),
        ),
        migrations.AddField(
            model_name='evento',
            name='inscritos',
            field=models.ManyToManyField(through='web_service.EventoInscrito', to='web_service.Inscrito'),
        ),
        migrations.AddField(
            model_name='equipetutor',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_service.Tutor'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='membros',
            field=models.ManyToManyField(through='web_service.EquipeTutor', to='web_service.Tutor'),
        ),
        migrations.AddField(
            model_name='encontro',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_service.Evento'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='encontro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_service.Encontro'),
        ),
    ]
