# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_service.Atividade'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='dir_audio',
            field=models.FileField(upload_to='sounds/'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='inscrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_service.Inscrito'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_service.Tutor'),
        ),
    ]
