# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0002_auto_20161031_0002'),
        ('web_service', '0002_auto_20161027_0205'),
    ]

    operations = [
    ]
