# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0003_merge_20161104_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
