# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0007_auto_20161120_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='observacao',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
