# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0008_feedback_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
