# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0009_auto_20161121_0306'),
        ('web_service', '0007_auto_20161120_2118'),
    ]

    operations = [
    ]
