# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0012_auto_20161125_1434'),
        ('web_service', '0010_merge_20161121_1937'),
    ]

    operations = [
    ]
