# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0013_merge_20161126_0446'),
        ('web_service', '0012_merge_20161125_2005'),
    ]

    operations = [
    ]
