# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0014_merge_20161205_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='dir_audio',
            field=models.FileField(null=True, upload_to='sounds/'),
        ),
    ]
