# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0015_auto_20161205_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='observacao',
            field=models.TextField(null=True),
        ),
    ]
